theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
auto-pairs = true
text-width = 100
auto-completion = true
completion-trigger-len = 1
completion-timeout = 5
preview-completion-insert = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
g = { q = ":reflow" }
