[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
# diagnosticsTrigger = "Save"
usePlaceholders = true
staticcheck = true
vulncheck = "Imports" # or "All"
gofumpt = true

[language-server.gopls.config.analyses]
unusedfunc = true
unusedparams = true
unreachable = true
unusedvariable = true

[language-server.gopls.config.hints]
compositeLiteralTypes = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = " " }
auto-format = true
language-servers = ["gopls"]
formatter = { command = "gofumpt" }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.emmet-lsp.config]
includeLanguages = { astro = "html", svelte = "html" }
showAbbreviationSuggestions = true
showExpandedAbbreviation = "always"
showSuggestionsAsSnippets = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-lsp"]
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]

[language-server.astro-ls.config]
typescript = { tsdk = "node_modules/typescript/lib" }

[[language]]
name = "astro"
auto-format = true
language-servers = ["astro-ls","emmet-lsp"]

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver","emmet-lsp"]
# formatter = { command = "prettier", args = ["--parser", "html"]}

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

[[language]]
name = "javascript"
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]


[[language]]
name = "typescript"
auto-format = true

[language.formatter]
command = "npx"
args = ["prettier", "--stdin-filepath", "%{buffer_name}"]

